"""изменения в бд

Revision ID: b035b389b558
Revises: 
Create Date: 2026-04-23 18:46:36.464514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'b035b389b558'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_table('comments')
    op.drop_table('discuss')
    op.drop_table('notification')
    op.drop_table('posts')
    op.drop_table('dislikes')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_checked')
        batch_op.drop_column('edition')

    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('discuss_id')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('discuss_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'])
        batch_op.create_foreign_key(None, 'discuss', ['discuss_id'], ['id'])
        batch_op.drop_column('message_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edition', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('is_checked', sa.BOOLEAN(), nullable=True))

    op.create_table('dislikes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_author', sa.INTEGER(), nullable=True),
    sa.Column('id_post', sa.INTEGER(), nullable=True),
    sa.Column('id_discuss', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_discuss'], ['discuss.id'], name=op.f('fk_dislikes_discuss')),
    sa.ForeignKeyConstraint(['id_post'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_author', 'id_post', name=op.f('uq_dislikes_author_post'))
    )
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_author', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.Column('views', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('type', sqlite.JSON(), nullable=True),
    sa.Column('image_name', sa.VARCHAR(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('is_news', sa.BOOLEAN(), nullable=True),
    sa.Column('official', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('from_user_id', sa.INTEGER(), nullable=True),
    sa.Column('post_id', sa.INTEGER(), nullable=True),
    sa.Column('discuss_id', sa.INTEGER(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('message', sa.VARCHAR(length=200), nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['discuss_id'], ['discuss.id'], name=op.f('fk_notification_discuss')),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discuss',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_author', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.Column('views', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('categories', sqlite.JSON(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_author', sa.INTEGER(), nullable=True),
    sa.Column('id_post', sa.INTEGER(), nullable=True),
    sa.Column('id_comment', sa.INTEGER(), nullable=True),
    sa.Column('id_discuss', sa.INTEGER(), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_author', sa.INTEGER(), nullable=True),
    sa.Column('id_post', sa.INTEGER(), nullable=True),
    sa.Column('id_discuss', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_discuss'], ['discuss.id'], name=op.f('fk_likes_discuss')),
    sa.ForeignKeyConstraint(['id_post'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_author', 'id_post', 'id_discuss', name=op.f('uq_likes_author_post_discuss'))
    )
    # ### end Alembic commands ###
